
CREATE ROLE bonita LOGIN PASSWORD 'bpm' CONNECTION LIMIT -1;
CREATE ROLE bizdata LOGIN PASSWORD 'bpm' CONNECTION LIMIT -1;

CREATE DATABASE bonita
  WITH OWNER = bonita
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'fr_FR.UTF-8'
       LC_CTYPE = 'fr_FR.UTF-8'
       CONNECTION LIMIT = -1;

GRANT CONNECT, TEMPORARY ON DATABASE bonita TO public;

GRANT ALL ON DATABASE bonita TO bonita;

CREATE DATABASE bizdata
  WITH OWNER = bizdata
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'fr_FR.UTF-8'
       LC_CTYPE = 'fr_FR.UTF-8'
       CONNECTION LIMIT = -1;

GRANT CONNECT, TEMPORARY ON DATABASE bizdata TO public;

GRANT ALL ON DATABASE bizdata TO bizdata;